### ISSUE TITLE
Groups visualization

### ISSUE THREAD

**Issue by dirkjanm** [dirkjanm/ldapdomaindump#2]
Look into ways to visualize complex group structures, maybe with a separate utility or with a command line client to just get all memberships of a useraccount

**Comment by omerule** [comment]
Iam working on this with visualising the nested group and members and NTFS ace.
https://github.com/omerule/knoper
Currenty i use VB and excel to extract the data from AD.
This data is then loaded into NEO4j db.
But i wan't to use Python and iam thinking of using "ldapdomaindump".
Only the group data dump has no "grep"  output.  
Is it possible to extend to output of "domain_users_by_group"  with a "grep"  variant?

Yours kindly
Ome Roel 
Netherlands

**Comment by dirkjanm** [comment]
The grouped output has no grep file, because all the users and their groups are already included in the user grep output (domain_users_by_group is just aggregated for viewing). For parsing I would recommend using the JSON files, they contain the raw data, which makes the parsing easier. Otherwise the domain_users.grep has a groups column.

**Comment by dirkjanm** [comment]
There is now `ldd2bloodhound` which converts .json files to CSV's for https://github.com/BloodHoundAD/BloodHound, which offers pretty nice visualization.
