### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by luolufang** [dirkjanm/ldapdomaindump#23]
LDAP is too big，so when i dump it。 it's out of memory

[*] Connecting to host...
[*] Binding to host
[+] Bind OK
[*] Starting domain dump
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ldap3\utils\asn1.py", line 121, in decode_sequence
    ber_len, ber_value_offset = compute_ber_size(get_bytes(message[start: start + 10]))
MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

**Comment by dirkjanm** [comment]
This is a know issue, see #10
