### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by DesBlock** [dirkjanm/ldapdomaindump#29]
![image](https://user-images.githubusercontent.com/7647070/77236253-50e87e80-6b93-11ea-9599-2b75fbcf5822.png)

Proposed fix is this, but I'm getting weird SID strings on the last value when doing so. Change line 350 to:
```
sid_value = format_sid(group.objectSid.value)
gid = int(sid_value.split('-')[-1])
```
![image](https://user-images.githubusercontent.com/7647070/77236324-d9671f00-6b93-11ea-8bbe-15bbb50411d0.png)

![image](https://user-images.githubusercontent.com/7647070/77236330-f3086680-6b93-11ea-985f-6b9809396275.png)

**Comment by dirkjanm** [comment]
are you sure this is not related to #26?

**Comment by DesBlock** [comment]
Quite possible, this came up while trying the Monteverde box from HTB. It is similar to the Forest box referenced in Issues #26. Feel free to close it. I appreciate your input on the reason for failure. Clarified some questions I have on the box.
