### ISSUE TITLE
I read your post https://dirkjanm.io/active-directory-forest-trusts-part-one-how-does-sid-filtering-work/, and here is some questions I want to ask

### ISSUE THREAD

**Issue by qwgrsftewg** [dirkjanm/ldapdomaindump#37]
here is my environment, I got a windows 7 x64 workstation in forest-a.local, and log on as superuser@forest-a.local, who is a member of "Enterprise Admins"  and "Domain Admins" group in forest-a.local, below is the output of klist:
![image](https://user-images.githubusercontent.com/64349502/93290182-d4082b80-f7e8-11ea-88b7-84c876f8fda8.png)

I have no idea how can I connect to server in forest-b.local, because I don't have a valid credential to connect with, I tried superuser@forest-a.local and administrator@forest-a.local, but neither of them are right, am I supposed to use administrator@forest-b.local? If so, I think my workstation would just send request to DC of forest-b.local, not DC of forest-a.local

**Comment by dirkjanm** [comment]
I don't really understand the question but this is not the place to ask
