### ISSUE TITLE
ldapdomaindump silently fails

### ISSUE THREAD

**Issue by blark** [dirkjanm/ldapdomaindump#4]
I was troubleshooting a problem with ntlmrelayx.py, and I think that ldapdomaindump is the cause. 

ntlmrelayx.py was never setting the global variable domainDumped = True because there was some silent error in the dump that was causing the function to return prematurely. Sure enough when I moved the line domainDumped = True to the top of the code (setting it before the domain dump was attempted) it works fine. 

I looked quickly at the ldapdomaindump code and it seems like there are lots of try: blocks that return nothing on error. It would be nice to know why this is failing and at least get a little feedback for troubleshooting purposes.

Thanks for the awesome work.

**Comment by dirkjanm** [comment]
If the variable isn't set then there must be some exception triggered that is not caught in a try block, since otherwise the code would just continue.
I think that the treading of ntlmrelayx somehow hides it.

To troubleshoot, I suggest changing the code [here](https://github.com/CoreSecurity/impacket/blob/master/examples/ntlmrelayx.py#L205) with an extra try/except block:
```python
try:
    domainDumper.domainDump()
except Exception, e:
    logging.error("Dumping domain info FAILED")
    logging.error(str(e))
```

This should give some more info about what is failing

**Comment by blark** [comment]
Thanks I will add that. I went into the source and added debugging it's dying at the getAllUsers() function. Adding the exception handler now to see why...

**Comment by dirkjanm** [comment]
I don't know how large the domain is that you are trying to dump, but it can take a while to get all the data. Did you try running the tool standalone (not as part of ntlmrelayx) to see if it produces an error then?

**Comment by blark** [comment]
You're totally right. I was just being impatient. DOH! Thanks!

**Comment by dirkjanm** [comment]
Yes good point, you could also add the exception handler from above so that in case something does go wrong, it will be shown properly.

**Comment by blark** [comment]
Done. They already accepted the pull, wow fast ;) Hey thanks again for the help and quick responses. 

I have another question regarding ntlmrelayx.py what is the best way to get in touch with you?

**Comment by dirkjanm** [comment]
Easiest is to email me at dirkjan [at] sanoweb.nl 
Closing this since it should be fixed now, thanks for the contribution :)
