### ISSUE TITLE
Output formatter error

### ISSUE THREAD

**Issue by neofito** [dirkjanm/ldapdomaindump#40]
Hi,

Microsoft [establishes](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/36565693-b5e4-4f37-b0a8-c1b12138e18e) that the trustType attribute contains one of the following values:

- TTD (TRUST_TYPE_DOWNLEVEL, 0x00000001)
- TTU (TRUST_TYPE_UPLEVEL, 0x00000002)
- TTM (TRUST_TYPE_MIT, 0x00000003)
- TTDCE (TRUST_TYPE_DCE, 0x00000004)

But using the latest stable version of ldapdomaindump I'm getting two values at least:

![image](https://user-images.githubusercontent.com/1921186/113252896-be5ddd80-92c4-11eb-97fe-a0a78be93ce0.png)

Thanks for your support

**Comment by dirkjanm** [comment]
thanks, pushed a fix for this, if you could retest this and see if it's solved that'd be great :)
