### ISSUE TITLE
How to use with Davmail?

### ISSUE THREAD

**Issue by DUOLabs333** [dirkjanm/ldapdomaindump#43]
Davmail provides a gateway between Microsoft's Exchange services to formats like Imap, Caldav, Carddav and LDAP. However, there's no username or password to enter. Leaving them blank gives you 
`KeyError: 'defaultnamingcontext'`

**Comment by dirkjanm** [comment]
Unfortunately ldapdomaindump is specifically written for Active Directory LDAP. Other directory formats are not supported, you'd be better off using a full ldap client such as Apache Directory Studio
