### ISSUE TITLE
Simple Authentication Error with UID username

### ISSUE THREAD

**Issue by Acters** [dirkjanm/ldapdomaindump#61]
Logging into a LDAP server with a user that is UID user instead of CN will result in an INVALID CREDENTIALS error.
https://serverfault.com/questions/448568/openldap-authentication-uid-vs-cn-issues

**Comment by dirkjanm** [comment]
You are linking to an issue that describes authenticating to openldap, not to Active Directory LDAP. ldapdomaindump doesn't work with other LDAP software.
