### ISSUE TITLE
Active output for large domains

### ISSUE THREAD

**Issue by mubix** [dirkjanm/ldapdomaindump#7]
Dump fails against large domains due to memory issues. It would be nice to be able to dump data as it is parsed so that in the event that the user's machine runs out of memory that they still get some of the data.

**Comment by mubix** [comment]
I spoke too soon, things worked out

**Comment by dirkjanm** [comment]
Yes this is a known issue as it currently tries to load everything in memory to correlate the data before writing it to disk.
I have it on my todo list to add a more memory-efficient mode, but it would require quite some changes.
