### ISSUE TITLE
Retrieve Unix attributes

### ISSUE THREAD

**Issue by andybissen** [dirkjanm/ldapdomaindump#8]
Hi,

It would be useful if the tool could retrieve Unix UID, GID, and default shell info per user, as well.

In Active Directory, the UID attribute is 'uidNumber', the GID attribute is 'gidNumber', and the shell attribute is 'loginShell'

Thanks

**Comment by dirkjanm** [comment]
Can you let me know if these attributes are present in the .json files? The .html files only show the most common attributes, while the .json files should contain all attributes.

**Comment by andybissen** [comment]
Ah, I didn't think to check there.  Yes, they are already in domain_users.json and the group GIDs are already in domain_groups.json

Thanks!

**Comment by dirkjanm** [comment]
Good to hear this solved it. Since those aren't very commonly used attributes (as far as I'm aware of) I won't add them to the HTML output, but I'll consider adding a feature which allows you to specify additional attributes to include in the HTML.
